### ISSUE TITLE
[Feature Request] Add support for multiple backends to persist trace data

### ISSUE THREAD

**Issue by ayansen** [ExpediaDotCom/haystack-traces#185]
Currently haystack traces supports only the cassandra backend. Adding a new backend would mean writing a new driver in haystack-traces-commons module and using it in the reader and indexer.
This design has a problem when we create multiple drivers all of the dependencies get added in the main jar and can cause conflict. 
This issue is created to discuss if we can come up with a cleaner way to add new backends for traces

**Comment by ayansen** [comment]
Proposed design for the new architecture is documented here : https://github.com/ExpediaDotCom/haystack-traces/wiki/Supporting-Multiple-Trace-Backends

**Comment by adriancole** [comment]
FYI in zipkin we are likely to move to armeria for grpc endpoints
